[phases.setup]
nixPkgs = [
  "php85"                     # PHP 8.5
  "php85Extensions.mysqli"    # ekstensi MySQLi
]

shell = ''
  echo "extension=mysqli.so" > $PHP_INI_DIR/conf.d/mysqli.ini
''

[start]
cmd = "php -S 0.0.0.0:$PORT"
